'use strict';
const countries={
 korea:{name:'South Korea',code:'KR',category:'INSIDE THE SHIELD',role:"The world’s memory layer",description:'KorMem Alliance, the successor to Samsung and SK Hynix, supplies the memory architectures on which frontier computing depends. Its strength comes from being indispensable to the other nodes.',relations:[['taiwan','Taiwan','Logic fabrication meets Korean memory.'],['japan','Japan','Materials and process expertise keep production viable.'],['us','United States','Security support becomes a demand for technology.']],tension:'A richer country, but a narrower economy. Who shares in the gains from indispensability?'},
 taiwan:{name:'Taiwan',code:'TW',category:'INSIDE THE SHIELD',role:'The frontier fabrication node',description:'NexFab, the successor consortium to TSMC, holds the highest-yield frontier logic processes. Manufacturing knowledge gives Taiwan a bargaining position that market size alone cannot buy.',relations:[['korea','South Korea','Memory and logic form a complementary system.'],['japan','Japan','Critical materials enable frontier yields.'],['china','China','Application markets remain open through firewalled subsidiaries.']],tension:'Indispensability brings security, but concentrates an entire society’s future in a handful of bottlenecks.'},
 japan:{name:'Japan',code:'JP',category:'INSIDE THE SHIELD',role:'The materials behind the frontier',description:'Advanced materials, equipment and process knowledge give Japanese suppliers control over less visible but essential bottlenecks. Quantum and biocomputing research adds influence of its own.',relations:[['taiwan','Taiwan','Process materials sustain advanced fabrication.'],['korea','South Korea','Trusted suppliers underpin memory production.'],['us','United States','Technology reciprocity strains an enduring alliance.']],tension:'Industrial success depends on cooperation with neighbours despite historical distrust and commercial rivalry.'},
 china:{name:'China',code:'CN',category:'MARKET & COUNTERFORCE',role:'A proving ground with upstream power',description:'China remains a major industrial and military power. Its robotics and biomedical markets attract island-chain firms, while control over critical inputs gives it a different source of leverage.',relations:[['taiwan','Taiwan','Selective market access; the core knowledge layer stays closed.'],['korea','South Korea','Demand for memory meets strict investment screening.'],['japan','Japan','Critical-mineral pressure tests supply security.']],tension:'China benefits from the technologies it cannot fully control. Disrupting the shield would damage its own economy.'},
 us:{name:'United States',code:'US',category:'ALLY & COMPETITOR',role:'The protector’s anxiety',description:'The 2058 Frontier Reciprocity Act makes continued security support a bargaining tool for technology transfer. Space launch and orbital infrastructure preserve American leverage.',relations:[['korea','South Korea','Talent quotas and licence-sharing become contested terms.'],['taiwan','Taiwan','The shield offers N−2 knowledge, two generations behind.'],['japan','Japan','Joint orbital projects bind competing partners together.']],tension:'Neither side can comfortably leave the alliance, and neither wants to remain the dependent partner.'},
 india:{name:'India',code:'IN',category:'PARTNER & ALTERNATIVE',role:'Design at scale; an alternative in waiting',description:'India becomes the largest application market for island-chain output and a major semiconductor producer by volume. Its design workforce complements the shield’s hard-to-replicate frontier yields.',relations:[['taiwan','Taiwan','Indian design; island-chain fabrication; Indian applications.'],['korea','South Korea','A vast application economy consumes advanced memory.'],['japan','Japan','Alternative investment limits the shield’s pricing power.']],tension:'India’s credible alternatives put a ceiling on how aggressively the shield can charge for indispensability.'},
 asean:{name:'Southeast Asia',code:'ASEAN',category:'PRODUCTION HINTERLAND',role:'The indispensable downstream network',description:'Assembly, testing, packaging and mature-node fabrication expand through Penang, Batam and Vietnamese coastal corridors. The region enables the frontier while remaining exposed to its decisions.',relations:[['taiwan','Taiwan','Packaging and assembly extend the fabrication chain.'],['korea','South Korea','Memory production depends on downstream capacity.'],['japan','Japan','Regional production draws on equipment and process networks.']],tension:'An indispensable contribution does not automatically translate into an equal share of power or value.'},
 europe:{name:'Europe',code:'EU',category:'REGULATOR & CUSTOMER',role:'Market access as leverage',description:'European vehicles and defence systems depend on island-chain silicon. Standards, sustainability rules and data governance become Europe’s tools for shaping the terms of access.',relations:[['taiwan','Taiwan','Frontier chips underpin European industrial systems.'],['korea','South Korea','Trusted-market rules shape memory and data infrastructure.'],['japan','Japan','Standards influence technology diffusion.']],tension:'Europe can regulate the market, but it cannot easily replace the suppliers on which that market depends.'},
 gulf:{name:'Gulf states',code:'GULF',category:'CAPITAL & ENERGY',role:'Buying a place beside the frontier',description:'Energy contracts, orbital infrastructure and sovereign investment give Gulf states a stake in the shield’s continuity. Carefully admitted non-voting capital does not buy control of core knowledge.',relations:[['korea','South Korea','Sovereign capital enters without controlling the core.'],['taiwan','Taiwan','Energy and investment support a demanding industrial system.'],['us','United States','Orbital infrastructure deepens interdependence.']],tension:'Financial ownership brings a stake in continuity, but not the right to direct the technological frontier.'}
};
const nodes={korea:{x:646,y:248,label:'SOUTH KOREA',sub:'MEMORY',lx:628,ly:215},japan:{x:778,y:253,label:'JAPAN',sub:'MATERIALS',lx:790,ly:283},taiwan:{x:576,y:374,label:'TAIWAN',sub:'FABRICATION',lx:603,ly:379},china:{x:380,y:264,label:'CHINA',lx:338,ly:246},india:{x:120,y:374,label:'INDIA',lx:92,ly:354},asean:{x:424,y:527,label:'SOUTHEAST ASIA',lx:420,ly:570},us:{x:880,y:172,label:'United States',external:true},europe:{x:880,y:370,label:'Europe',external:true},gulf:{x:880,y:435,label:'Gulf states',external:true}};
const links=[['taiwan','korea','supply',-30],['korea','japan','supply',-32],['japan','taiwan','supply',65],['china','korea','pressure',-45],['china','taiwan','pressure',-35],['china','japan','pressure',-100],['us','korea','pressure',-10],['us','taiwan','pressure',70],['us','japan','supply',0],['india','taiwan','supply',70],['india','korea','supply',-85],['india','japan','pressure',-115],['asean','korea','supply',55],['asean','taiwan','supply',-18],['asean','japan','supply',70],['europe','korea','pressure',-22],['europe','taiwan','supply',20],['europe','japan','supply',25],['gulf','korea','supply',80],['gulf','taiwan','supply',25],['gulf','us','supply',70]];
const places=[
 {id:'memory',label:'Memory campus',x:17,y:29,category:'WORK & VALUE',location:'THE KORMEM CAMPUS',title:'The memory behind everything',moment:'An engineer checks a tray of living-compute cartridges as fabrication robots stack photonic memory layers. Some are bound for neighbourhood clinics; others for orbital data centres.',explanation:'KorMem Alliance, the successor to Samsung and SK Hynix, controls advanced memory architectures. Its position rests on accumulated process knowledge, trusted suppliers and engineering education that cannot simply be purchased or relocated.',question:'When one industry becomes indispensable, how much of the city must organise itself around it?',country:'korea'},
 {id:'research',label:'Quantum garden',x:55,y:28,category:'KNOWLEDGE & POWER',location:'THE Q-GARDEN',title:'The frontier has moved',moment:'Beneath the Q-Garden’s terraced roof, a cryogenic core models new materials beside living biocomputing cultures. A visiting US team is cleared to see only the N−2 systems.',explanation:'By the 2050s, quantum and biocomputing breakthroughs emerge within the island chain. The US seeks reciprocal technology transfer; the shield restricts what it shares to N−2 knowledge, two generations behind the frontier.',question:'Can scientific collaboration flourish when knowledge is also a nation’s security guarantee?',country:'us'},
 {id:'mobility',label:'Departure terminal',x:92,y:34,category:'TALENT & FREEDOM',location:'THE DEPARTURE TERMINAL',title:'Valuable. And less free.',moment:'An autonomous maglev capsule docks at the departure gate. An engineer’s biometric travel pass turns amber: the journey is booked, but their knowledge-clearance review is still pending.',explanation:'Exit vetting, outbound talent quotas and non-compete periods tighten as the shield protects its knowledge. Engineers become some of its most treasured—and least mobile—resources. Civil-liberties campaigns challenge the restrictions.',question:'Where does protecting a shared capability become controlling a person’s life?',country:'us'},
 {id:'clinic',label:'Regenerative clinic',x:85,y:61,category:'CARE & TRUST',location:'THE RENEWAL CLINIC',title:'Care, grown to order',moment:'A care robot guides a resident in a soft mobility suit past tissue-growing pods. Their personalised repair patch is ready; permission to reuse its biomedical data is not.',explanation:'Biocomputing, neuromedicine and medical robotics extend the value of advanced substrates. Strict compute-audit and data-provenance regimes try to make abundant computing compatible with privacy. Trust is part of what the shield exports.',question:'Who gets to decide when better care justifies more inference about a person?',country:'europe'},
 {id:'dividend',label:'Civic plaza',x:60,y:82,category:'AUTOMATION & DISTRIBUTION',location:'THE CIVIC PLAZA',title:'A share of the shield',moment:'Under self-adjusting solar canopies, a former logistics worker checks a chip-dividend payment. Courier robots pass by carrying tissue cultures and groceries.',explanation:'Automation displaces logistics, retail and clerical work. Following strike waves in Korea and Japan, sovereign funds redistribute a legislated share of semiconductor rents. The dividend shares prosperity, but it does not replace every lost role or source of purpose.',question:'Is a share of the income enough to make people feel part of the future?',country:'korea'},
 {id:'neighbourhood',label:'Older neighbourhood',x:24,y:76,category:'PROSPERITY & BELONGING',location:'THE OLDER NEIGHBOURHOOD',title:'Beyond the bright campus',moment:'A repair robot unfolds beside a tiled-roof shop to service an ageing mobility suit. Across the road, a premium renewal clinic offers a treatment the shopkeeper cannot afford.',explanation:'Returns concentrate in frontier firms, metropolitan corridors and specialised workers. Other sectors struggle to attract talent; ageing and demographic decline weaken domestic consumption. National strength can coexist with a narrowing local economy.',question:'What happens to a society when the work that protects it also defines whose work matters?',country:'korea'}
];

window.SCENARIO_DATA={countries,nodes,links,places};
