'use strict';
(()=>{
 const {countries,nodes,places}=window.SCENARIO_DATA;
 const stages=window.SCENARIO_TIMELINE;let currentYear=2026;
 const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],NS='http://www.w3.org/2000/svg';
 const svg=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,String(v)));return e};
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const baseBox=[0,90,1000,563];   // height grows to keep room for the filters (reserveFilterRoom); networks fill y 90–630, labels included
 const world=q('#world-map'),graphic=q('#graphic'),cityArt=q('#city-art'),finalImage=q('#city-final'),ground=q('.scene-ground'),hotspots=q('#hotspots'),caption=q('#canvas-caption');
 let careReady=false,yearChanging=false,pendingYear=2026,nodeSetKey='';
 // 2070 can bring its own actor network (s1-2070-network.js): nodes, arrowed links, link types and the entry node.
 const ENTRY=stages[2070].entry||'care',entryName=()=>stages[2070].countries[ENTRY].name;
 const stageNodes=year=>stages[year].nodes||nodes,setKeyFor=year=>stages[year].nodes?String(year):stages[year].placeholder?'placeholder':'base';
 const closeBoxFor=()=>{const n=stageNodes(2070)[ENTRY];return [n.x-115,n.y-64.745,230,129.49]};
 const defaultFilters=[['supply','Resources & care'],['pressure','Pressure & limits']];
 const years=[2026,2050,2070],slider=q('#year-slider');
 let state='map',selected='care',filter='all',currentPlace=0,transitionID=0,frameID=0,animations=[];
 const visited=new Set();
 const districts=window.CITY_CONTOURS.map(d=>({...d}));
 // SVG clip paths preserve exact image registration at every responsive size.
 districts.forEach(d=>{const el=document.createElement('div');el.className='district';el.dataset.district=d.id;const layer=svg('svg',{viewBox:'0 0 1672 941','aria-hidden':'true'});const defs=svg('defs'),clip=svg('clipPath',{id:'subject-'+d.id,clipPathUnits:'userSpaceOnUse'});clip.append(svg('path',{d:d.path,'clip-rule':'evenodd'}));defs.append(clip);const image=svg('image',{href:finalImage.getAttribute('src'),width:1672,height:941,'clip-path':'url(#subject-'+d.id+')'});layer.append(defs,image);el.append(layer);q('#districts').append(el);d.el=el});
 function edgePoint(n,tx,ty){const hw=(n.w||170)/2+5,hh=(n.h||56)/2+5,dx=tx-n.x,dy=ty-n.y,t=Math.min(dx?hw/Math.abs(dx):Infinity,dy?hh/Math.abs(dy):Infinity);return [+(n.x+dx*t).toFixed(1),+(n.y+dy*t).toFixed(1)]}
 // on:true centres a link's label on the line itself.
 // pa / pb pin a link's ends to a box side ('t','r','b','l') at an offset from its centre, so links of one type can leave an actor side by side.
 function drawActorLinks(){const set=stageNodes(currentYear);stages[currentYear].links.forEach(l=>{const A=set[l.a],B=set[l.b],port=(n,p)=>{const hw=(n.w||170)/2+5,hh=(n.h||56)/2+5,[side,o]=p;return side==='l'?[n.x-hw,n.y+o]:side==='r'?[n.x+hw,n.y+o]:side==='t'?[n.x+o,n.y-hh]:[n.x+o,n.y+hh]},p0=l.pa?port(A,l.pa):[A.x,A.y],p1=l.pb?port(B,l.pb):[B.x,B.y],dx=p1[0]-p0[0],dy=p1[1]-p0[1],len=Math.hypot(dx,dy)||1,bend=l.bend||0,cx=(p0[0]+p1[0])/2-dy/len*bend,cy=(p0[1]+p1[1])/2+dx/len*bend,[x0,y0]=l.pa?p0:edgePoint(A,cx,cy),[x1,y1]=l.pb?p1:edgePoint(B,cx,cy);const el=svg('path',{d:`M${x0} ${y0} Q${cx.toFixed(1)} ${cy.toFixed(1)} ${x1} ${y1}`,class:`map-link ${l.type}`,'marker-end':`url(#arrow-${l.type})`});if(l.both)el.setAttribute('marker-start',`url(#arrow-${l.type})`);const parts=[el];if(l.label){let lx=l.lx??(.25*x0+.5*cx+.25*x1),ly=l.ly??(.25*y0+.5*cy+.25*y1-5),anchor=l.anchor||'middle';const lines=l.label.split('\n').length;if(l.at!==undefined){const t=l.at,u=1-t,px=u*u*x0+2*u*t*cx+t*t*x1,py=u*u*y0+2*u*t*cy+t*t*y1,tx=2*u*(cx-x0)+2*t*(x1-cx),ty=2*u*(cy-y0)+2*t*(y1-cy),tl=Math.hypot(tx,ty)||1,s=l.on?0:Math.sign(l.off||1),g=Math.abs(l.off||6),nx=-ty/tl*s,ny=tx/tl*s;const w=Math.max(...l.label.split('\n').map(x=>x.length))*4.6,h=lines*12,dd=g+Math.abs(nx)*w/2+Math.abs(ny)*h/2;anchor='middle';lx=px+nx*dd;ly=py+ny*dd+3.5-(lines-1)*6.5;l._place={px,py,nx,ny,g,lines}}const text=svg('text',{x:lx.toFixed(1),y:ly.toFixed(1),class:`link-label ${l.type}${l.on?' on-line':''}`,'text-anchor':anchor});l.label.split('\n').forEach((line,i)=>{const span=svg('tspan',{x:text.getAttribute('x'),dy:i?13:0});span.textContent=line;text.append(span)});if(l.group)text.dataset.group=l.group;if(l._place)text._place=l._place;parts.push(text)}parts.forEach(e=>{e.dataset.a=l.a;e.dataset.b=l.b;e.dataset.type=l.type});q('#connections').append(...parts);parts.forEach(e=>{const pl=e._place;if(!pl)return;const b=e.getBBox();if(!b.width)return;const dd=pl.g+Math.abs(pl.nx)*b.width/2+Math.abs(pl.ny)*b.height/2,x=pl.px+pl.nx*dd,y=pl.py+pl.ny*dd+3.5-(pl.lines-1)*6.5;e.setAttribute('x',x.toFixed(1));e.setAttribute('y',y.toFixed(1));e.querySelectorAll('tspan').forEach(s=>s.setAttribute('x',x.toFixed(1)))})})}
 function drawLinks(){q('#connections').replaceChildren();if(stages[currentYear].nodes){drawActorLinks();return}stages[currentYear].links.forEach(([a,b,type,c,label,tx,ty])=>{const A=nodes[a],B=nodes[b];const el=svg('path',{d:`M${A.x} ${A.y} Q${(A.x+B.x)/2+c*.15} ${(A.y+B.y)/2+c} ${B.x} ${B.y}`,class:`map-link ${type}`});const text=svg('text',{x:tx,y:ty,class:`link-label ${type}`,'text-anchor':'middle'});text.textContent=label;[el,text].forEach(e=>{e.dataset.a=a;e.dataset.b=b;e.dataset.type=type});q('#connections').append(el,text)})}
 function mapCaption(){caption.innerHTML='<span class="legend-chip"></span>'+stages[currentYear].caption+'<span class="caption-right">'+currentYear+' / Select a city type</span>'}
 function lockTimeline(locked){q('#timeline').classList.toggle('locked',locked);slider.disabled=locked;qa('[data-year]').forEach(b=>b.disabled=locked||!!(stages[b.dataset.year]||{}).disabled)}
 function renderYear(year){
  currentYear=year;careReady=false;graphic.dataset.year=String(year);const newNetwork=setKeyFor(year)!==nodeSetKey;buildNodes(year);if(newNetwork&&stages[year].focus)selected=stages[year].focus;renderFilters(year);q('#country-panel').classList.toggle('brief',!!stages[year].nodes);graphic.classList.toggle('under-dev',!!stages[year].placeholder);q('#country-panel').classList.toggle('under-dev',!!stages[year].placeholder);graphic.classList.toggle('actor-network',!!stages[year].nodes);q('#dev-note').textContent=stages[year].placeholder||'';
  if(!stages[year].countries[selected])selected=stages[year].focus||(year===2070?ENTRY:'care');
  q('#timeline-note').textContent=stages[year].note;q('#scale-label').textContent='01 / '+year;
  qa('[data-year]').forEach(b=>{const active=Number(b.dataset.year)===year;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
  world.setAttribute('aria-label',`City-type relationships in ${year}. Select a city type for information.`+(year===2070?` Select ${entryName()} twice to enter the care city.`:''));
  q('#load-error').hidden=true;drawLinks();selectCountry(selected);mapCaption();
  q('#announcer').textContent=year+'. '+stages[year].title+'. '+stages[year].note+(year===2070?` The care city is available through ${entryName()}.`:'');
 }

 function sliderPosition(value){slider.value=String(value);slider.style.setProperty('--progress',value/2*100+'%');const year=years[Math.round(value)];slider.setAttribute('aria-valuetext',year+' — '+stages[year].title)}
 async function selectYear(year){
  if(state!=='map'||!stages[year])return;
  pendingYear=year;
  if(yearChanging||year===currentYear)return;
  yearChanging=true;careReady=false;graphic.setAttribute('aria-busy','true');q('#country-panel').inert=true;enableMap(false);
  const surfaces=[q('#connections'),caption,q('#country-panel'),q('#timeline-note')],networkParts=[q('#countries'),q('#stage-decor'),q('#filters'),q('.network-eyebrow'),q('#dev-note')];
  async function fade(list,from,to,duration){const batch=list.map(el=>el.animate([{opacity:from},{opacity:to}],{duration:reduced.matches?60:duration,easing:'ease-in-out',fill:'forwards'}));await Promise.allSettled(batch.map(a=>a.finished));list.forEach(el=>el.style.opacity=String(to));batch.forEach(a=>a.cancel())}
  try{
   while(pendingYear!==currentYear){
    const target=pendingYear,from=currentYear;
    if(stages[from].nodes&&stages[target].nodes&&!reduced.matches){
     // Between two actor networks (2026 and 2070): actors in both glide to their new place, the rest fade; new actors fade in while they move, then the links and panel fade back in.
     const before=stageNodes(from),after=stageNodes(target),parts=[...surfaces,q('#stage-decor'),q('#filters'),q('.network-eyebrow')];
     // An actor whose name or subtitle changes keeps a copy of its old text, which fades out while the new text fades in.
     const renamed=id=>after[id]&&(before[id].label!==after[id].label||before[id].sub!==after[id].sub),oldText={};
     qa('#countries .node').forEach(g=>{if(renamed(g.dataset.country))oldText[g.dataset.country]=[...g.querySelectorAll(':scope > text')].map(t=>t.cloneNode(true))});
     await fade([...parts,...qa('#countries .node').filter(g=>!after[g.dataset.country])],1,0,240);
     renderYear(target);
     const nodesNow=qa('#countries .node'),entering=nodesNow.filter(g=>!before[g.dataset.country]);
     entering.forEach(g=>g.style.opacity='0');
     const oldLabels=[],newLabels=[];
     Object.entries(oldText).forEach(([id,texts])=>{const g=q(`#countries .node[data-country="${id}"]`);if(!g)return;const a=before[id],b=after[id],wrap=svg('g',{class:'label-swap',transform:`translate(${b.x-a.x} ${b.y-a.y})`,'aria-hidden':'true'});wrap.append(...texts);const fresh=[...g.querySelectorAll(':scope > text')];fresh.forEach(t=>t.style.opacity='0');g.append(wrap);oldLabels.push(wrap);newLabels.push(...fresh)});
     const moves=nodesNow.filter(g=>before[g.dataset.country]).map(g=>{const a=before[g.dataset.country],b=after[g.dataset.country];return g.animate([{transform:`translate(${a.x-b.x}px,${a.y-b.y}px)`},{transform:'translate(0px,0px)'}],{duration:760,easing:'cubic-bezier(.65,0,.35,1)'})});
     await Promise.all([Promise.allSettled(moves.map(m=>m.finished)),entering.length?fade(entering,0,1,400):null,oldLabels.length?fade(oldLabels,1,0,400):null,newLabels.length?fade(newLabels,0,1,400):null]);
     oldLabels.forEach(w=>w.remove());
     await fade(parts,0,1,300);
     continue;
    }
    const list=setKeyFor(target)!==nodeSetKey?[...surfaces,...networkParts]:surfaces;
    await fade(list,1,0,220);
    renderYear(target);
    await fade(list,0,1,340);
   }
  }finally{
   [...surfaces,...networkParts].forEach(el=>el.style.opacity='1');qa('#countries .node,#countries text').forEach(g=>g.style.opacity='');qa('.label-swap').forEach(w=>w.remove());yearChanging=false;graphic.setAttribute('aria-busy','false');q('#country-panel').inert=false;enableMap(true);
  }
 }
 // A stage marked disabled (2050 while it is being written) cannot be selected: the slider snaps past it and its button stays disabled.
 const off=i=>!!(stages[years[i]]||{}).disabled,snap=v=>{const i=Math.round(v),cur=years.indexOf(currentYear);if(!off(i))return i;const j=v<i?i-1:v>i?i+1:cur;return j>=0&&j<years.length&&!off(j)?j:cur},step=(i,d)=>{while(i>0&&i<years.length-1&&off(i))i+=d;return off(i)?years.indexOf(currentYear):i};
 qa('.timeline-track [data-year]').forEach(b=>{if((stages[b.dataset.year]||{}).disabled){b.disabled=true;b.setAttribute('aria-disabled','true')}});
 slider.addEventListener('input',()=>{if(state!=='map')return;sliderPosition(Number(slider.value));selectYear(years[snap(Number(slider.value))])});
 slider.addEventListener('change',()=>{if(state!=='map')return;const index=snap(Number(slider.value));sliderPosition(index);selectYear(years[index])});
 slider.addEventListener('keydown',e=>{if(state!=='map')return;const offsets={ArrowLeft:-1,ArrowDown:-1,ArrowRight:1,ArrowUp:1};if(!(e.key in offsets)&&e.key!=='Home'&&e.key!=='End')return;e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?2:step(Math.max(0,Math.min(2,Math.round(Number(slider.value))+offsets[e.key])),offsets[e.key]);sliderPosition(index);selectYear(years[index])});
 qa('.timeline-track [data-year]').forEach((b,i)=>{b.addEventListener('click',()=>{if(state!=='map'||off(i))return;sliderPosition(i);selectYear(years[i])});b.addEventListener('keydown',e=>{const keys=['ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(e.key)||state!=='map')return;e.preventDefault();const buttons=qa('.timeline-track [data-year]');let next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;while(off(next))next=(next+(e.key==='ArrowLeft'||e.key==='End'?2:1))%3;buttons[next].focus();sliderPosition(next);selectYear(years[next])})});
 function bindNode(g,id){g.dataset.country=id;g.addEventListener('click',()=>activateCountry(id));g.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();activateCountry(id)}});q('#countries').append(g)}
 function cityRoleNode(id,n,i){const g=svg('g',{class:'node '+id,role:'button',tabindex:0,'aria-label':`Explore ${countries[id].name}`,'aria-pressed':'false'});g.append(svg('rect',{x:n.x-96,y:n.y-43,width:192,height:86,rx:7,class:'node-card'}));const num=svg('text',{x:n.x-80,y:n.y-26,class:'role-number'});num.textContent=String(i+1).padStart(2,'0');const t=svg('text',{x:n.x,y:n.y-7,'text-anchor':'middle',class:'node-label'});t.textContent=n.label;const sub=svg('text',{x:n.x,y:n.y+13,'text-anchor':'middle',class:'node-sub'});sub.textContent=n.sub;g.append(num,t,sub);bindNode(g,id)}
 function actorNode(id,n,name){const w=n.w||170,h=n.h||56,g=svg('g',{class:`node actor kind-${n.kind}`,role:'button',tabindex:0,'aria-label':`Explore ${name}`,'aria-pressed':'false'});g.append(svg('rect',{x:n.x-w/2,y:n.y-h/2,width:w,height:h,rx:6,class:'node-card'}));if(n.kind!=='hub')g.append(svg('rect',{x:n.x-w/2,y:n.y-h/2,width:4,height:h,rx:2,class:'kind-mark'}));const lines=n.label.split('\n'),block=11+(lines.length-1)*18+(n.sub?17:0)+3,first=n.y-block/2+11.5;lines.forEach((line,i)=>{const t=svg('text',{x:n.x,y:(first+i*18).toFixed(1),'text-anchor':'middle',class:'node-label'});t.textContent=line;g.append(t)});if(n.sub){const s=svg('text',{x:n.x,y:(first+(lines.length-1)*18+17).toFixed(1),'text-anchor':'middle',class:'node-sub'});s.textContent=n.sub;g.append(s)}bindNode(g,id)}
 function drawDecor(st){const decor=q('#stage-decor');decor.replaceChildren();if(st.ring){const r=st.ring;decor.append(svg('ellipse',{cx:r.cx,cy:r.cy,rx:r.rx,ry:r.ry,class:'compact-ring'}))}if(st.kinds){const legend=svg('g',{class:'kind-legend'});let x=962;[...st.kinds].reverse().forEach(([kind,label])=>{const t=svg('text',{x,y:130,'text-anchor':'end'});t.textContent=label.toUpperCase();const w=label.length*7.6+6;legend.append(t,svg('rect',{x:x-w-12,y:122,width:8,height:8,rx:2,class:`kind-chip kind-${kind}`}));x-=w+28});decor.append(legend)}}
 function buildNodes(year){const key=setKeyFor(year);if(key===nodeSetKey)return;nodeSetKey=key;const st=stages[year];q('#countries').replaceChildren();drawDecor(st);q('.network-eyebrow').textContent=st.eyebrow||'CITY ROLES / EAST ASIA & THE PACIFIC';if(st.nodes)Object.entries(st.nodes).forEach(([id,n])=>actorNode(id,n,st.countries[id].name));else Object.entries(nodes).forEach(([id,n],i)=>cityRoleNode(id,n,i));if(state!=='map'||yearChanging)qa('.node').forEach(n=>n.setAttribute('tabindex','-1'))}
 // Filter buttons list the network's relationship types (all four in 2070, even one without lines yet).
 function renderFilters(year){const st=stages[year],types=st.linkTypes||defaultFilters;if(!types.some(([t])=>t===filter))filter='all';const box=q('#filters');box.replaceChildren();[['all','All relationships'],...types].forEach(([t,label,full])=>{const b=document.createElement('button');b.dataset.filter=t;if(full){b.title=full;b.setAttribute('aria-label',full)}b.setAttribute('aria-pressed',String(t===filter));b.classList.toggle('selected',t===filter);if(t!=='all'){const i=document.createElement('i');i.className=t;b.append(i)}b.append(document.createTextNode(label));box.append(b)})}
 function updateCareHint(){
  const available=currentYear===2070,ready=available&&selected===ENTRY&&careReady,name=entryName();
  const node=q(`.node[data-country="${ENTRY}"]`);
  if(node)node.setAttribute('aria-label',ready?`${name}: activate again to enter the care city`:`${name}: view information`);
  if(state==='map'||state==='exiting'){
   q('#instruction').classList.toggle('click-prompt',available);q('#instruction').innerHTML=available?(ready?`Click <strong>${name}</strong> again to enter the care city.`:`Click <strong>${name}</strong> to view its information.`):'Explore city relationships.';
   q('.care-tip').innerHTML=!available?'Explore this year’s city-type information.':ready?`Read the information here. Click <strong>${name}</strong> again when you’re ready to enter the care city.`:`Select <strong>${name}</strong> to read its information. Click it again to enter the care city.`;
  }
 }
 function activateCountry(id){
  if(state!=='map'||yearChanging)return;
  if(currentYear===2070&&id===ENTRY&&selected===ENTRY&&careReady){enterCity();return}
  selectCountry(id);careReady=currentYear===2070&&id===ENTRY;updateCareHint();
  if(careReady)q('#announcer').textContent=`${entryName()} information is displayed. Activate it again to enter the care city.`;
 }
 function selectCountry(id){if(!stages[currentYear].countries[id])return;careReady=false;selected=id;const c=stages[currentYear].countries[id];['name','code','category','role','description','tension'].forEach(key=>q('#country-'+key).textContent=c[key]);q('#country-panel').dataset.kind=(stageNodes(currentYear)[id]||{}).kind||'';q('#relationships').replaceChildren();c.relations.forEach(([target,name,description])=>{const b=document.createElement('button');b.className='relationship';const strong=document.createElement('b');strong.textContent=name;const text=document.createElement('span');text.textContent=description;b.append(strong,text);b.dataset.targetCountry=target;b.addEventListener('click',()=>activateCountry(target));q('#relationships').append(b)});qa('[data-country]').forEach(el=>{const active=el.dataset.country===id;el.classList.toggle('selected',active);if(el.getAttribute('role')==='button')el.setAttribute('aria-pressed',String(active))});updateLinks();updateCareHint()}
 function updateLinks(){const ring=stages[currentYear].ring,inRing=!!ring&&selected===ring.node,member=id=>inRing&&ring.members.includes(id);const outline=q('.compact-ring');if(outline)outline.classList.toggle('active',inRing);qa('.map-link,.link-label').forEach(el=>{el.classList.toggle('focused',el.dataset.a===selected||el.dataset.b===selected||(el.dataset.group||'').split(' ').includes(selected)||(member(el.dataset.a)&&member(el.dataset.b)));el.classList.toggle('filtered',filter!=='all'&&el.dataset.type!==filter)})}
 q('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;qa('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});updateLinks()});
 function enableMap(enabled){world.style.pointerEvents=enabled?'auto':'none';world.setAttribute('aria-hidden',String(!enabled));qa('.node').forEach(n=>n.setAttribute('tabindex',enabled?'0':'-1'))}
 function enableCity(enabled){hotspots.inert=!enabled;hotspots.setAttribute('aria-hidden',String(!enabled));hotspots.classList.toggle('ready',enabled);cityArt.setAttribute('aria-hidden',String(!enabled))}
 function cancelAnimations(){transitionID++;cancelAnimationFrame(frameID);animations.forEach(a=>a.cancel());animations=[];return transitionID}
 function play(el,frames,options){const a=el.animate(frames,{fill:'both',...options});animations.push(a);return a.finished.catch(()=>{})}
 function tweenBox(from,to,duration,id){return new Promise(resolve=>{const start=performance.now();function step(now){if(id!==transitionID){resolve();return}const t=Math.min(1,(now-start)/duration),e=1-Math.pow(1-t,3);world.setAttribute('viewBox',from.map((n,i)=>(n+(to[i]-n)*e).toFixed(3)).join(' '));if(t<1)frameID=requestAnimationFrame(step);else resolve()}frameID=requestAnimationFrame(step)})}
 function setHeader(city){q('#scale-label').textContent=city?'02 / CARE CITY · 2070':'01 / '+currentYear;q('#page-title').textContent=city?'Inside the care city.':'Silver City Compact.';q('#instruction').classList.remove('click-prompt');q('#instruction').innerHTML=city?'Select a level to explore its role.':`Click <strong>${entryName()}</strong> to view its information.`;q('#country-panel').hidden=city;q('#city-panel').hidden=!city;q('#filters').hidden=city;q('#footer-note').textContent=city?'Five service levels and a basement.':'Roles can overlap. Links show dependencies, not routes.';q('.info-panel').scrollTop=0;if(!city)updateCareHint()}
 function imageReady(){if(finalImage.complete)return Promise.resolve(finalImage.naturalWidth>0);return new Promise(resolve=>{finalImage.addEventListener('load',()=>resolve(true),{once:true});finalImage.addEventListener('error',()=>resolve(false),{once:true})})}
 async function enterCity(){if(state!=='map'||yearChanging||currentYear!==2070)return;state='loading';lockTimeline(true);graphic.dataset.view='loading';q('#instruction').classList.remove('click-prompt');q('#instruction').textContent='';q('#return-map').hidden=false;q('#announcer').textContent='Opening the care city.';graphic.setAttribute('aria-busy','true');const loaded=await imageReady();if(state!=='loading')return;if(!loaded){state='map';lockTimeline(false);graphic.dataset.view='map';setHeader(false);q('#return-map').hidden=true;graphic.setAttribute('aria-busy','false');q('#load-error').hidden=false;return}
  const id=cancelAnimations(),short=reduced.matches;state='entering';graphic.dataset.view='entering';enableMap(false);enableCity(false);q('#return-map').hidden=false;q('#return-map').focus({preventScroll:true});cityArt.style.visibility='visible';finalImage.style.opacity='0';q('#load-error').hidden=true;
  const work=[play(world,[{opacity:1},{opacity:1,offset:.35},{opacity:0}],{duration:short?170:1050,easing:'ease-in-out'}),tweenBox(baseBox,closeBoxFor(),short?1:1050,id),play(ground,[{opacity:0},{opacity:1}],{duration:short?160:800,delay:short?0:380}),play(caption,[{opacity:1},{opacity:0}],{duration:short?70:280}),play(q('#filters'),[{opacity:1},{opacity:0}],{duration:short?70:280})];
  districts.forEach(d=>work.push(play(d.el,[{opacity:0,transform:short?'none':`translate(${d.x}%,${d.y}%)`},{opacity:1,transform:'translate(0%,0%) scale(1)'}],{duration:short?180:850,delay:short?0:360,easing:'cubic-bezier(.16,1,.3,1)'})));
  work.push(play(finalImage,[{opacity:0},{opacity:1}],{duration:short?160:320,delay:short?0:900,easing:'ease-in-out'}));
  await Promise.allSettled(work);if(id!==transitionID)return;animations.forEach(a=>a.cancel());animations=[];ground.style.opacity='1';world.style.opacity='0';caption.style.opacity='0';finalImage.style.opacity='1';districts.forEach(d=>d.el.style.opacity='0');state='city';graphic.dataset.view='city';setHeader(true);caption.innerHTML='<span class="legend-chip"></span>CARE CITY / 2070<span class="caption-right">Explore the six levels</span>';enableCity(true);graphic.setAttribute('aria-busy','false');play(caption,[{opacity:0},{opacity:1}],{duration:short?1:250});await play(hotspots,[{opacity:0},{opacity:1}],{duration:short?1:340});if(id===transitionID)q('#announcer').textContent='The care city is open. Six levels are available to explore.';
 }
 async function returnMap(country=selected){if(state==='map')return;const previous=state;const id=cancelAnimations(),short=reduced.matches;state='exiting';lockTimeline(true);graphic.dataset.view='exiting';graphic.setAttribute('aria-busy','true');enableCity(false);enableMap(false);q('#load-error').hidden=true;selectCountry(country);setHeader(false);hotspots.style.opacity='0';caption.style.opacity='0';ground.style.opacity='1';finalImage.style.opacity='1';const closeBox=closeBoxFor();world.setAttribute('viewBox',closeBox.join(' '));
  const work=[play(world,[{opacity:0},{opacity:1}],{duration:short?140:750,delay:short?0:180}),tweenBox(closeBox,baseBox,short?1:980,id),play(ground,[{opacity:1},{opacity:0}],{duration:short?120:600,delay:short?0:200}),play(finalImage,[{opacity:1},{opacity:0}],{duration:short?100:250}),play(q('#filters'),[{opacity:0},{opacity:1}],{duration:short?100:400,delay:short?0:600})];
  if(previous==='city'&&!short)districts.forEach((d,i)=>work.push(play(d.el,[{opacity:1,transform:'translate(0%,0%)'},{opacity:0,transform:`translate(${d.x*.45}%,${d.y*.45}%)`}],{duration:540,delay:i*28,easing:'ease-in'})));
  await Promise.allSettled(work);if(id!==transitionID)return;cancelAnimations();state='map';lockTimeline(false);graphic.dataset.view='map';world.style.opacity='1';world.setAttribute('viewBox',baseBox.join(' '));ground.style.opacity='0';cityArt.style.visibility='hidden';finalImage.style.opacity='0';districts.forEach(d=>d.el.style.opacity='0');hotspots.style.opacity='0';caption.style.opacity='1';mapCaption();q('#return-map').hidden=true;enableMap(true);graphic.setAttribute('aria-busy','false');q(`.node[data-country="${country}"]`).focus({preventScroll:true});q('#announcer').textContent=`Network restored. Select ${entryName()} to read its information, then activate it again to enter the care city.`;
 }
 q('#return-map').addEventListener('click',()=>returnMap());q('#retry-image').addEventListener('click',()=>{q('#load-error').hidden=true;const src='assets/care-tower-2070.webp?retry='+Date.now();finalImage.src=src;districts.forEach(d=>d.el.querySelector('image').setAttribute('href',src));enterCity()});
 places.forEach((p,i)=>{const b=document.createElement('button');b.className='pin'+(p.side==='left'||p.x>=75?' left':'');b.style.left=p.x+'%';b.style.top=p.y+'%';b.dataset.place=p.id;b.setAttribute('aria-label',`Explore ${p.label}`);b.setAttribute('aria-haspopup','dialog');b.innerHTML='<span class="pin-circle">'+p.level+'</span><span class="pin-label"></span>';b.querySelector('.pin-label').textContent=p.label;b.addEventListener('click',()=>openPlace(i));hotspots.append(b);const list=document.createElement('button');list.dataset.place=p.id;list.setAttribute('aria-haspopup','dialog');const num=document.createElement('span');num.textContent=p.level;list.append(num,document.createTextNode(p.label));list.addEventListener('click',()=>openPlace(i));q('#place-list').append(list)});
 const placeDialog=q('#place-dialog');
 function openPlace(i){if(state!=='city')return;currentPlace=i;const p=places[i];visited.add(p.id);q('#place-category').textContent=p.category;q('#place-location').textContent=p.location;q('#place-title').textContent=p.title;q('#place-moment').textContent=p.moment;q('#place-explanation').textContent=p.explanation;q('#place-progress').textContent=String(i+1).padStart(2,'0')+' / 06';q('#next-place').textContent=i===5?'Top level':'Next level';q('#explored').textContent=visited.size+' / 6 explored';qa('[data-place]').forEach(el=>{const v=visited.has(el.dataset.place);el.classList.toggle('visited',v)});if(!placeDialog.open)placeDialog.showModal();placeDialog.scrollTop=0;placeDialog.querySelector('.close-dialog').focus({preventScroll:true})}
 q('#next-place').addEventListener('click',()=>openPlace((currentPlace+1)%places.length));q('#trace').addEventListener('click',()=>{const p=places[currentPlace],to=(stages[2070].placeCountry||{})[p.id]||p.country;fadeClose(placeDialog,()=>returnMap(to))});
 // Dialogs fade in through CSS and fade out here before they actually close; the timer closes them even if
 // the browser skips the animation (for example in a background tab).
 function fadeClose(d,then){if(!d.open||d.classList.contains('closing'))return;let finished=false;const done=()=>{if(finished)return;finished=true;d.classList.remove('closing');d.close();if(then)then()};if(reduced.matches){done();return}d.classList.add('closing');d.addEventListener('animationend',e=>{if(e.target===d)done()},{once:true});setTimeout(done,300)}
 qa('dialog').forEach(d=>{d.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();fadeClose(d)}});d.addEventListener('cancel',e=>{e.preventDefault();fadeClose(d)});d.addEventListener('close',()=>d.classList.remove('closing'));d.querySelector('.close-dialog').addEventListener('click',()=>fadeClose(d));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)fadeClose(d)}})});q('#about-button').addEventListener('click',()=>q('#about-dialog').showModal());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!qa('dialog').some(d=>d.open)&&state!=='map')returnMap()});
 // The canvas fills the area inside an even margin; the map or diagram is centred in it, and the city illustration
 // (with its cut-outs and pins) keeps its 1672 × 941 proportions in a centred box given by --img-*.
 // On wider screens the relationship filters sit inside the canvas, so the map's base view gains room underneath
 // them (in map units, which depend on the canvas size) and nothing in the map or diagram sits behind the buttons.
 // --map-bleed: the map canvas extends this many px beyond the fitted network on each side, so a thinner frame does not move the actors.
 function reserveFilterRoom(w,h){const f=q('#filters'),H=540;if(!f||!matchMedia('(min-width:681px)').matches){baseBox[0]=0;baseBox[1]=90;baseBox[2]=1000;baseBox[3]=563;return}const m=parseFloat(getComputedStyle(graphic).getPropertyValue('--map-bleed'))||0,iw=Math.max(1,w-2*m),ih=Math.max(1,h-2*m);const px=f.offsetHeight+22,first=px*H/Math.max(1,ih-px),scale=Math.min(iw/1000,ih/(H+first)),b=m/scale;baseBox[0]=-b;baseBox[1]=90-b;baseBox[2]=1000+2*b;baseBox[3]=H+px/scale+2*b;if(state==='map'&&!yearChanging)world.setAttribute('viewBox',baseBox.join(' '))}
 function fitGraphic(){const area=q('.visual-area'),cs=getComputedStyle(area),w=Math.max(1,area.clientWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight)),h=Math.max(1,area.clientHeight-parseFloat(cs.paddingTop)-parseFloat(cs.paddingBottom)),iw=Math.min(w,h*1672/941),ih=iw*941/1672;graphic.style.width=w+'px';graphic.style.height=h+'px';graphic.style.setProperty('--img-w',iw+'px');graphic.style.setProperty('--img-h',ih+'px');graphic.style.setProperty('--img-x',(w-iw)/2+'px');graphic.style.setProperty('--img-y',(h-ih)/2+'px');reserveFilterRoom(w,h)}new ResizeObserver(fitGraphic).observe(q('.visual-area'));fitGraphic();renderYear(2026);sliderPosition(0);enableCity(false);
})();
