'use strict';
// Scenario 3: Baeksang. The 2070 detail follows the supplied narratives.
const countries={
 korea:{name:'South Korea',code:'KR',category:'FESTIVAL CENTRE',role:'Prestige draws people in',description:'Baeksang in Seoul is the world’s most watched cultural week. Its festivals, platforms and markets help decide which work travels, who gets paid and where young creators choose to live. Busan and Seoul attract trainees even as East Asia ages.',relations:[['japan','Japan','Tokyo is a major market and an alternative home for creators.'],['asean','Southeast Asia','Bangkok and Jakarta finance and make new work.'],['africa','Africa','Creators and audiences move between Lagos and Korean cities.']],tension:'The circuit creates opportunity, but Seoul’s prestige can crowd out its partners.'},
 japan:{name:'Japan',code:'JP',category:'MARKET & RIGHTS',role:'A second centre of gravity',description:'Tokyo Convergence is the circuit’s largest market week. Japanese games and animation travel globally, while artists license their skills and receive royalties. When MIRA’s creators moved a show from Seoul to Tokyo over pay, fans and sponsors followed.',relations:[['korea','South Korea','Studios and fans move between two centres.'],['asean','Southeast Asia','Games, rights and production teams cross borders.']],tension:'Rights only protect people when smaller studios follow them too.'},
 taiwan:{name:'Taiwan',code:'TW',category:'TALENT & PRODUCTION',role:'A place to make and learn',description:'Taiwan courts studios with training grants, culture visas and production support. A creator may study in one circuit city, make work in another and reach audiences far beyond East Asia.',relations:[['korea','South Korea','Training and co-production connect talent to Baeksang.'],['asean','Southeast Asia','Creators share production networks.']],tension:'Can smaller centres gain recognition without copying the biggest festival’s tastes?'},
 china:{name:'China',code:'CN',category:'PLATFORMS & PARALLEL PRESTIGE',role:'A commercial giant on two circuits',description:'Chinese platforms distribute stories from Korea, Japan, Africa and Latin America to enormous audiences. At home, the state runs separate prizes and cultural institutes. Creators such as Wei work in both systems, sometimes under different names.',relations:[['korea','South Korea','Platforms seek global rights to Baeksang work.'],['india','India','Distribution reaches South Asian audiences.'],['asean','Southeast Asia','Regional stories travel through Chinese platforms.']],tension:'Commercial reach is vast, while rules on expression divide creators’ working lives.'},
 india:{name:'India',code:'IN',category:'AUDIENCE & RECOGNITION',role:'A vast young audience asks for a voice',description:'Mumbai’s partner week brings one of the world’s largest young audiences into the circuit. Indian platforms buy rights across South Asia, while creators in India and Pakistan ask to be full participants rather than guests.',relations:[['korea','South Korea','Baeksang earns from viewers who ask to share its prizes.'],['asean','Southeast Asia','Mumbai and Jakarta connect fast-growing markets.']],tension:'Why do Indian viewers bring so much revenue but Indian work win so few prizes?'},
 asean:{name:'Southeast Asia',code:'ASEAN',category:'MULTIPLE CREATIVE CENTRES',role:'Stories made across the circuit',description:'Bangkok Storyworlds finances studios; Jakarta’s Nusantara Assembly joins games, learning and design. Vietnamese animators, Thai producers, Indonesian performers and Filipino fans shape the work seen on Baeksang’s stage.',relations:[['korea','South Korea','Talent and stories travel to Busan and Seoul.'],['japan','Japan','Finance, character rights and fans cross borders.'],['india','India','Jakarta and Mumbai share growing audiences.']],tension:'Growth brings influence, but small studios may still keep long hours and weak protections.'},
 us:{name:'United States',code:'US',category:'A RESPECTED RIVAL',role:'The Oscars remain, with a different reach',description:'The Oscars remain a respected American ceremony, but no single Western institution delivers the world’s verdict. American firms object to Asian cultural dominance even as directors and stars join the circuit.',relations:[['korea','South Korea','Prestige and talent now move both ways.'],['japan','Japan','Games and films compete for global attention.']],tension:'What happens when a familiar measure of cultural status is no longer universal?'},
 europe:{name:'Europe',code:'EU',category:'CO-PRODUCER & TALENT',role:'Joining a circuit led elsewhere',description:'European directors premiere in Seoul and Tokyo, and young musicians train there. European actors and co-producers stay influential, even as the biggest festivals and markets sit in East Asia.',relations:[['korea','South Korea','Actors, films and training paths move toward Seoul.'],['japan','Japan','Conservatories and markets connect talent to Tokyo.']],tension:'Access to the circuit can mean accepting rules set elsewhere.'},
 africa:{name:'Africa',code:'AFR',category:'CREATORS & AUDIENCES',role:'Lagos joins and challenges the circuit',description:'Amara came from Lagos to Busan on a culture-training visa. Lagos Screen Week offers its own stage. Local creators worry when children know Korean songs better than Yoruba stories.',relations:[['korea','South Korea','Migration and fans connect Lagos to Busan.'],['asean','Southeast Asia','Artists and studios collaborate across the circuit.']],tension:'Global connection must leave room for local stories and control.'},
 gulf:{name:'Gulf states',code:'GULF',category:'TOURING & CAPITAL',role:'A winter stage for the circuit',description:'Dubai and Doha host the circuit’s winter concert season. Audiences, sponsors and travel markets connect Gulf cities to East Asian performers and festivals.',relations:[['korea','South Korea','Tours and sponsors follow global fan communities.'],['asean','Southeast Asia','Performers travel through multiple regional stages.']],tension:'A profitable tour stop may still have little say in what wins prestige.'}
};
// Actor cards retain the country detail panels while replacing geographic placement.
const nodes={
 us:{x:130,y:201,label:'WESTERN INDUSTRY',sub:'UNITED STATES',kind:'western'},
 europe:{x:130,y:321,label:'EUROPE',sub:'CO-PRODUCTION',kind:'western'},
 africa:{x:130,y:513,label:'AFRICA',sub:'CREATORS & FANS',kind:'audience'},
 japan:{x:319,y:242,label:'JAPAN',sub:'RIGHTS & MARKETS',kind:'industry'},
 china:{x:319,y:501,label:'CHINA',sub:'PLATFORMS',kind:'industry'},
 korea:{x:510,y:215,label:'SOUTH KOREA',sub:'BAEKSANG',kind:'government'},
 taiwan:{x:510,y:516,label:'TAIWAN',sub:'TRAINING',kind:'industry'},
 asean:{x:701,y:242,label:'SOUTHEAST ASIA',sub:'STUDIOS',kind:'industry'},
 india:{x:867,y:321,label:'INDIA',sub:'AUDIENCE & PRIZES',kind:'audience'},
 gulf:{x:867,y:513,label:'GULF STATES',sub:'TOURS & FANS',kind:'audience'}
};
// A small set of conceptual ties keeps the system legible at each year.
const links=[
 ['korea','japan','supply',0],['korea','asean','supply',0],
 ['korea','us','pressure',0],['korea','africa','supply',0],
 ['korea','china','pressure',0],['asean','india','supply',0],
 ['korea','gulf','supply',0],['taiwan','korea','supply',0],
 ['europe','japan','supply',0]
];
const places=[
 {id:'arrival',label:'Arrival concourse',x:84,y:78,category:'MIGRATION & GENERATIONS',location:'SEOUL ARRIVAL CONCOURSE',title:'Who comes, and who stays',moment:'Amara arrives from Busan with Linh and Mr Park. She came from Lagos at seventeen to learn character design; he is seventy-one and advises the studio on games for older players.',explanation:'Culture visas, training and creative work bring young people into ageing East Asian cities. Older audiences have time, money and stories of their own. Places outside the circuit can still lose people and schools.',question:'Which places benefit when culture draws talent across borders?',country:'africa'},
 {id:'judges',label:'Judges’ hall',x:27,y:21,category:'RIGHTS & CREATIVE LABOUR',location:'THE JUDGES’ HALL',title:'The work behind the work',moment:'Judges ask Amara’s team for the licence to Ms Sato’s digital colour work, a record of each royalty, and proof that Mr Park will be paid if his shipyard stories return in a sequel.',explanation:'The Baeksang Charter on Synthetic Creativity sets rules for consent, provenance and payment when faces, voices or skills are copied. Festivals can refuse awards and platforms can pause releases. Small studios are harder to hold to the same standard.',question:'Who can enforce a creator’s rights after their work has travelled?',country:'japan'},
 {id:'market',label:'Rights market',x:19,y:48,category:'MONEY & DISTRIBUTION',location:'THE RIGHTS MARKET',title:'Who pays whom',moment:'A Chinese platform bids to carry Amara’s game worldwide. An Indian platform wants South Asian rights, and a fan trust asks to buy part of its art archive.',explanation:'Platforms and investors trade more than films or games: characters, memberships, travel, learning and livelihoods move together. China’s platforms are central even while its state runs a separate prestige system.',question:'When a story becomes a global business, who should own its future value?',country:'china'},
 {id:'circuit',label:'Circuit pavilion',x:80,y:41,category:'PRESTIGE & PARTICIPATION',location:'THE PARTNERSHIP PAVILION',title:'Many centres, uneven power',moment:'Delegates compare Tokyo’s market, Bangkok’s studio finance, Jakarta’s assembly and Mumbai’s partner festival. Lagos and São Paulo ask for room to grow on their own terms.',explanation:'Baeksang is a leading switchboard, not the only centre. Young audiences across Africa, South Asia, Southeast Asia and the Gulf support the circuit, yet access to its biggest prizes remains contested.',question:'Can a cultural circuit be shared if one festival sets the terms?',country:'asean'},
 {id:'forum',label:'Open forum',x:48,y:44,category:'WHO IS LEFT OUT',location:'THE PUBLIC FORUM',title:'The costs in plain sight',moment:'A Mumbai producer asks why Indian viewers bring so much revenue but Indian work wins so few prizes. Trainees argue about long hours, rent and games designed to be hard to stop playing.',explanation:'Celebrated studios do not represent every worker. Some newcomers are paid less, small studios ignore labour rules, and places with no creative industry keep shrinking. Game levies fund recovery clinics.',question:'Whose success is counted when a cultural economy is called successful?',country:'india'},
 {id:'arena',label:'Festival arena',x:56,y:28,category:'FANDOM & COLLECTIVE POWER',location:'THE BAEKSANG ARENA',title:'The stage can move',moment:'MIRA appears on the open-roof stage. Human artists make her; a fan trust can veto uses of her face and voice. Older fans fill the seats while younger fans stand below.',explanation:'When MIRA’s artists were underpaid, their cooperative moved a show from Seoul to Tokyo. Fans, flights and sponsors followed. Organised fandoms gain leverage, while a few global stars concentrate attention.',question:'Who holds power when a performer belongs to a cooperative and her fans?',country:'korea'}
];
window.SCENARIO_DATA={countries,nodes,links,places};
